language: php

env:
    global:
        secure: "Lm7vG9PYbgBB7av4S4U5Rk0/8kwm9ntMNW2pHTQwxCeXD2ITjkmOYTei7fc2pBo6A+D2iwuUNO/B38RDMZ6ug/eauo5MFhRdvwFJk5BVgHi6Iz92P0mlPPnKKD+lgiiu/mBZ2p6sWs2JxRwFXm18erYJrPkzvYUmr53t1/f8QC8xRRxdg08ot668LWKUcW4btpa5Rq6RhyZaZWzpDmQ8fX20zUTzk9HOWZOj942Aux6yjm7CAm+Fue2BA63f3LY32ofqiIbTUj7svT3PIUlIXYmWzwcyMC8iUoYmR4eMQh6zUgG3+wo9oTLdNw9oy0nEJM7zU3IkV6vz94apQaXEAk+nPmR4l3w0HUSd4Pw6ZTmByRwBoz9LBAWMimk4Yq5Qs0a8/+Wuwz7yBUyh2HBY7vC/3SNqocc2kLUPnbtQuTsbUHAk3mVQdXUgGvPEB+k7VEAQqdyn+nUDDIgjv0nnNdkHWFY5jGWdf5/hkPmpW1yS+O3bjxOlE2clMrJS9SZz9JKg+Wg9tcb7ue9DZqlSBzaYqypC4yCpLNcOABhxROxt+TlNZCADyYwyNMToAk0LJ9egF2hZPEFGYm1KOwvv4q+ymj5U9qibAkOdcH12JTbCfO1esOhJNhT5U+j4JvgJvmm9SQO3CCEyyTLin4CA8EB/NSIx7xWtN8OLlX1Z9js="

php:
  - 5.6

before_script:
    - travis_retry curl -O https://download.sculpin.io/sculpin.phar
    - travis_retry php sculpin.phar install

script: 
    - php sculpin.phar generate --env=prod

after_success:
    - travis_retry bin/deploy
